package com.online.shop.dao;

import com.online.shop.pojo.ProductType;
import com.online.shop.pojo.ProductTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTypeMapper {

    List<ProductType> selectAllProductType();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int countByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int deleteByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    List<ProductType> selectByExample(ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByExample(@Param("record") ProductType record, @Param("example") ProductTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_type
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByPrimaryKey(ProductType record);
}