package com.online.shop.dao;

import com.online.shop.pojo.Sysuser;
import com.online.shop.pojo.SysuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int countByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int deleteByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int insert(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int insertSelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    List<Sysuser> selectByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    Sysuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sysuser record, @Param("example") SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByExample(@Param("record") Sysuser record, @Param("example") SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByPrimaryKeySelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sysuser
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    int updateByPrimaryKey(Sysuser record);
}