package com.online.shop.pojo;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.address
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.regist_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Date registDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.login_name
     *
     * @return the value of t_customer.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.login_name
     *
     * @param loginName the value for t_customer.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.password
     *
     * @return the value of t_customer.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.password
     *
     * @param password the value for t_customer.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.phone
     *
     * @return the value of t_customer.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.phone
     *
     * @param phone the value for t_customer.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.address
     *
     * @return the value of t_customer.address
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.address
     *
     * @param address the value for t_customer.address
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.is_valid
     *
     * @return the value of t_customer.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.is_valid
     *
     * @param isValid the value for t_customer.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.regist_date
     *
     * @return the value of t_customer.regist_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.regist_date
     *
     * @param registDate the value for t_customer.regist_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }
}