package com.online.shop.pojo;

import java.util.Date;

public class Sysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.email
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.create_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sysuser.role
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    private Integer role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.id
     *
     * @return the value of t_sysuser.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.id
     *
     * @param id the value for t_sysuser.id
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.name
     *
     * @return the value of t_sysuser.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.name
     *
     * @param name the value for t_sysuser.name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.login_name
     *
     * @return the value of t_sysuser.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.login_name
     *
     * @param loginName the value for t_sysuser.login_name
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.password
     *
     * @return the value of t_sysuser.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.password
     *
     * @param password the value for t_sysuser.password
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.phone
     *
     * @return the value of t_sysuser.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.phone
     *
     * @param phone the value for t_sysuser.phone
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.email
     *
     * @return the value of t_sysuser.email
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.email
     *
     * @param email the value for t_sysuser.email
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.is_valid
     *
     * @return the value of t_sysuser.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.is_valid
     *
     * @param isValid the value for t_sysuser.is_valid
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.create_date
     *
     * @return the value of t_sysuser.create_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.create_date
     *
     * @param createDate the value for t_sysuser.create_date
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sysuser.role
     *
     * @return the value of t_sysuser.role
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sysuser.role
     *
     * @param role the value for t_sysuser.role
     *
     * @mbggenerated Sat Jul 21 03:33:53 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    @Override
    public String toString() {
        return "Sysuser{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", loginName='" + loginName + '\'' +
                ", password='" + password + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", isValid=" + isValid +
                ", createDate=" + createDate +
                ", role=" + role +
                '}';
    }
}